export const BASE_PERSON_NODE_WIDTH = 200;
export const BASE_MARITAL_NODE_WIDTH = 10;
export const BASE_SIBLINGS_SPACING = 270;
export const BASE_MARITAL_SPACING = 180;
export const BASE_GENERATIONS_SPACING = 250;
